#!/usr/bin/env python3
"""Generate the stable CLI and configuration references.

The source tables live here so documentation changes are reviewed alongside
the command/configuration surface. Use --check in CI to detect drift.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import click
from typer.main import get_command

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def markdown_cell(value: object) -> str:
    """Return a deterministic Markdown table cell across operating systems."""
    text = value.as_posix() if isinstance(value, Path) else str(value)
    return " ".join(text.replace("|", "\\|").split()) or "—"


def option_type(option: click.Option) -> str:
    if isinstance(option.type, click.Choice):
        return " | ".join(str(choice) for choice in option.type.choices)
    return option.type.name.upper()


def option_rows(command: click.Command) -> list[str]:
    rows = []
    for parameter in command.params:
        if not isinstance(parameter, click.Option) or parameter.hidden:
            continue
        flags = ", ".join(
            f"`{flag}`" for flag in (*parameter.opts, *parameter.secondary_opts)
        )
        default = "required" if parameter.required else markdown_cell(parameter.default)
        rows.append(
            f"| {flags} | {option_type(parameter)} | {default} | "
            f"{markdown_cell(parameter.help or '')} |"
        )
    return rows


def command_section(title: str, command: click.Command) -> str:
    description = markdown_cell(command.help or "")
    rows = option_rows(command)
    table = "\n".join(rows) if rows else "| — | — | — | No options |"
    return (
        f"## {title}\n\n{description}\n\n"
        "| Option | Type | Default | Purpose |\n"
        "|---|---|---|---|\n"
        f"{table}"
    )


def cli_reference() -> str:
    from pocarchitect.cli import app

    root_command = get_command(app)
    sections = [command_section("Main command", root_command)]
    sections.extend(
        command_section(f"Command: `{name}`", command)
        for name, command in root_command.commands.items()
    )
    commands = "\n".join(
        f"| `{name}` | {markdown_cell(command.help or '')} |"
        for name, command in root_command.commands.items()
    )
    return (
        "# CLI Reference\n\n"
        "Generated directly from Typer/Click command metadata by "
        "`python scripts/generate_docs.py`; it does not depend on terminal layout or platform path separators.\n\n"
        + "\n\n".join(sections)
        + "\n\n## Commands\n\n"
        "| Command | Purpose |\n"
        "|---|---|\n"
        f"{commands}" + "\n\n## Safe examples\n\n"
        "```text\n"
        "python -m pocarchitect preflight --provider local --offline\n"
        "python -m pocarchitect --url https://github.com/example/poc --no-ingest --dry-run --no-color\n"
        "python -m pocarchitect batch-status --batch-state reports/batch_progress.json\n"
        "```\n"
    )


CONFIG_REFERENCE = """# Configuration Reference

Generated by `python scripts/generate_docs.py`.

| Name | Required when | Secret | Purpose |
|---|---|---|---|
| `XAI_API_KEY` | `--provider xai` | Yes | xAI provider credential |
| `OPENAI_API_KEY` | `--provider openai` | Yes | OpenAI provider credential |
| `GROQ_API_KEY` | `--provider groq` | Yes | Groq provider credential |
| `--base-url` | `--provider local` | No | OpenAI-compatible local endpoint (default `http://localhost:11434/v1`) |
| `--output-dir` | custom output location | No | Report destination |
| `--batch-state` | custom batch ledger | No | JSON progress/resume state |
| `--yes` | source ingestion or batch reset | No | Explicit noninteractive confirmation |
| `--format json` | automation | No | Stable JSON Lines output |
| `--no-color` | accessibility/logging | No | Disable ANSI styling |

Put provider keys in a local `.env` file. Never commit `.env`, print its values,
or include credentials in reports or issue diagnostics.
"""


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    results = [
        write_or_check(ROOT / "docs" / "cli-reference.md", cli_reference(), args.check),
        write_or_check(
            ROOT / "docs" / "configuration-reference.md", CONFIG_REFERENCE, args.check
        ),
    ]
    if args.check and not all(results):
        print("Generated documentation is stale. Run: python scripts/generate_docs.py")
        return 1
    print(
        "Generated documentation is up to date."
        if args.check
        else "Generated documentation."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
