#!/usr/bin/env python3
"""Generate the stable CLI and configuration references.

The source tables live here so documentation changes are reviewed alongside
the command/configuration surface. Use --check in CI to detect drift.
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CLI_REFERENCE = """# CLI Reference

Generated by `python scripts/generate_docs.py`.

| Option/command | Default | Purpose |
|---|---|---|
| `--url`, `-u` | required unless `--batch` | Single GitHub PoC URL |
| `--batch`, `-b` | none | Text file containing one URL per line |
| `--batch-state` | `reports/batch_progress.json` | Resumable batch progress ledger |
| `--provider`, `-p` | `xai` | `xai`, `openai`, `groq`, or `local` |
| `--model`, `-m` | provider-specific | Model name |
| `--output-dir` | `./reports` | Report and default batch-ledger directory |
| `--no-ingest` | false | Do not clone source content |
| `--dry-run` | false | Build the prompt without an LLM call |
| `--verbose`, `-v` | false | Show extra ingestion details |
| `--version`, `-V` | false | Print the package version |
| `preflight --offline` | false | Check installation without requiring a provider key |

Run `python -m pocarchitect --help` for the runtime-generated help output.
"""

CONFIG_REFERENCE = """# Configuration Reference

Generated by `python scripts/generate_docs.py`.

| Name | Required when | Secret | Purpose |
|---|---|---|---|
| `XAI_API_KEY` | `--provider xai` | Yes | xAI provider credential |
| `OPENAI_API_KEY` | `--provider openai` | Yes | OpenAI provider credential |
| `GROQ_API_KEY` | `--provider groq` | Yes | Groq provider credential |
| `--base-url` | `--provider local` | No | OpenAI-compatible local endpoint |
| `--output-dir` | custom output location | No | Report destination |
| `--batch-state` | custom batch ledger | No | JSON progress/resume state |

Put provider keys in a local `.env` file. Never commit `.env`, print its values,
or include credentials in reports or issue diagnostics.
"""


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    results = [
        write_or_check(ROOT / "docs" / "cli-reference.md", CLI_REFERENCE, args.check),
        write_or_check(
            ROOT / "docs" / "configuration-reference.md", CONFIG_REFERENCE, args.check
        ),
    ]
    if args.check and not all(results):
        print("Generated documentation is stale. Run: python scripts/generate_docs.py")
        return 1
    print(
        "Generated documentation is up to date."
        if args.check
        else "Generated documentation."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
