#!/usr/bin/env python3
"""Generate the stable CLI and configuration references.

The source tables live here so documentation changes are reviewed alongside
the command/configuration surface. Use --check in CI to detect drift.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]

ANSI_ESCAPE = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")


def runtime_help(*arguments: str) -> str:
    """Capture the Typer-owned help text so docs cannot drift from CLI metadata."""
    environment = {**os.environ, "NO_COLOR": "1", "FORCE_COLOR": "0"}
    result = subprocess.run(
        [sys.executable, "-m", "pocarchitect", *arguments, "--help"],
        cwd=ROOT,
        capture_output=True,
        check=True,
        encoding="utf-8",
        env=environment,
    )
    plain_help = ANSI_ESCAPE.sub("", result.stdout)
    return "\n".join(line.rstrip() for line in plain_help.splitlines()).strip()


def cli_reference() -> str:
    sections = [
        ("Main command", ()),
        ("Provider preflight", ("preflight",)),
        ("Batch recovery status", ("batch-status",)),
        ("Batch recovery reset", ("batch-reset",)),
    ]
    rendered_sections = []
    for title, arguments in sections:
        rendered_sections.append(
            f"## {title}\n\n```text\n{runtime_help(*arguments)}\n```"
        )
    return (
        "# CLI Reference\n\n"
        "Generated from Typer command metadata by `python scripts/generate_docs.py`. "
        "CI fails when this runtime reference is stale.\n\n"
        + "\n\n".join(rendered_sections)
        + "\n\n## Safe examples\n\n"
        "```text\n"
        "python -m pocarchitect preflight --provider local --offline\n"
        "python -m pocarchitect --url https://github.com/example/poc --no-ingest --dry-run --no-color\n"
        "python -m pocarchitect batch-status --batch-state reports/batch_progress.json\n"
        "```\n"
    )


CONFIG_REFERENCE = """# Configuration Reference

Generated by `python scripts/generate_docs.py`.

| Name | Required when | Secret | Purpose |
|---|---|---|---|
| `XAI_API_KEY` | `--provider xai` | Yes | xAI provider credential |
| `OPENAI_API_KEY` | `--provider openai` | Yes | OpenAI provider credential |
| `GROQ_API_KEY` | `--provider groq` | Yes | Groq provider credential |
| `--base-url` | `--provider local` | No | OpenAI-compatible local endpoint (default `http://localhost:11434/v1`) |
| `--output-dir` | custom output location | No | Report destination |
| `--batch-state` | custom batch ledger | No | JSON progress/resume state |
| `--yes` | source ingestion or batch reset | No | Explicit noninteractive confirmation |
| `--format json` | automation | No | Stable JSON Lines output |
| `--no-color` | accessibility/logging | No | Disable ANSI styling |

Put provider keys in a local `.env` file. Never commit `.env`, print its values,
or include credentials in reports or issue diagnostics.
"""


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    results = [
        write_or_check(ROOT / "docs" / "cli-reference.md", cli_reference(), args.check),
        write_or_check(
            ROOT / "docs" / "configuration-reference.md", CONFIG_REFERENCE, args.check
        ),
    ]
    if args.check and not all(results):
        print("Generated documentation is stale. Run: python scripts/generate_docs.py")
        return 1
    print(
        "Generated documentation is up to date."
        if args.check
        else "Generated documentation."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
